export let cityName = [
  { zh: '臺北市', en: 'Taipei' },
  { zh: '桃園市', en: 'Taoyuan' },
  { zh: '新北市', en: 'NewTaipei' },
  { zh: '新竹市', en: 'Hsinchu' },
  { zh: '苗栗縣', en: 'MiaoliCounty' },
  { zh: '臺中市', en: 'Taichung' },
  { zh: '嘉義市', en: 'Chiayi' },
  { zh: '臺南市', en: 'Tainan' },
  { zh: '高雄市', en: 'Kaohsiung' },
  { zh: '屏東縣', en: 'PingtungCounty' },
  { zh: '金門縣', en: 'KinmenCounty' },
];

export let routeCityName = [
  { zh: '基隆市', en: 'Keelung' },
  { zh: '臺北市', en: 'Taipei' },
  { zh: '新北市', en: 'NewTaipei' },
  { zh: '桃園市', en: 'Taoyuan' },
  { zh: '新竹縣', en: 'HsinchuCounty' },
  { zh: '苗栗縣', en: 'MiaoliCounty' },
  { zh: '臺中市', en: 'Taichung' },
  { zh: '南投縣', en: 'NantouCounty' },
  { zh: '彰化縣', en: 'ChanghuaCounty' },
  { zh: '雲林縣', en: 'YunlinCounty' },
  { zh: '嘉義縣', en: 'ChiayiCounty' },
  { zh: '嘉義市', en: 'Chiayi' },
  { zh: '臺南市', en: 'Tainan' },
  { zh: '高雄市', en: 'Kaohsiung' },
  { zh: '宜蘭縣', en: 'YilanCounty' },
  { zh: '花蓮縣', en: 'HualienCounty' },
  { zh: '臺東縣', en: 'TaitungCounty' },
  { zh: '屏東縣', en: 'PingtungCounty' },
  { zh: '金門縣', en: 'KinmenCounty' },
  { zh: '澎湖縣', en: 'PenghuCounty' },
];
